kind: Service             # Defines to create service type object
apiVersion: v1
metadata:
   name: cycle
   labels:
     app: cycle
spec:
  ports:
     - port: 8080        #container port exposed
       targetport: 80     # pods port
       nodeport: 31200
  selector:
     app: cycle           # Apply this service to any pods which has a specific labels
  type: LoadBalancer      # specifies the service type i.e clusterIP or Nodeport
